macro(generate_translation_unit_file ModuleName SourceFiles)
    file(WRITE ${CMAKE_BINARY_DIR}/${ModuleName}.rtcxx.cpp "")
    foreach(SourceFile ${${SourceFiles}})
        string(FIND ${SourceFile} "." DotPos REVERSE)
        string(SUBSTRING ${SourceFile} ${DotPos} 15 FileExt)
        if(FileExt STREQUAL ".h")
            file(APPEND ${CMAKE_BINARY_DIR}/${ModuleName}.rtcxx.cpp "#include \"${SourceFile}\"\n")
        endif()
    endforeach()
endmacro()